const cards = [
    {desc:'It your birthday or somethin. Collect $#O from everyone', others:10, you:0},
    {desc:'Bank error in your favor! Collect $#Y', others:0, you:250},
    {desc:'Bank error not in your favor! Lose $#Y', others:0, you:-250},
    {desc:'You are loser. Lose $#Y.', others:0, you:-100},
    {desc:'Wear pussy hat. Collect $#Y.', others:0, you:150},
    {desc:'Donate to your friends feminist organization! Theyre not actually feminists :(. They embezzle the money. Lose $#T.', others:-40, you:0},
    {desc:'Get posted to cringe compilation. That makes you lose $#Y somehow', others:0, you:-200},
    {desc:'Eat a turd lol. That was a bet. everyone owes you $#O', others:25, you:0},
    {desc:'get dared to eat a turd. Spit it out. OH no you lose $#Y!!', others:0, you:-100},
    {desc:'ur rich uncle penny bags gives you a penny bag. it has pennies totalling $#Y', others:0, you:1},
    {desc:'post cringe to twitter. get cancelled off twitter.. this costs you $#Y!!', others:0, you:-50},
    {desc:'punch a bourgeoisie! he sues you a LOT! $#Y to be exact', others:0, you:-500},
    {desc:'Win lottery of $#Y!! But youre generous. Pay everyone $#O.', others:-50, you:500},
    {desc:'die', others:0, you:-9999},
    {desc:'offer tech support to old people. Take $#O from everyone', others:100, you:0},
    {desc:'steal $#Y from bank (bc they were rude about ur hat)', others:0, you:200},
    {desc:'start a business and become girlboss! This endeavor costs you $#Y', others:0, you:-250},
    {desc:'start a business and become girlboss! wow! you earn $#Y.', others:0, you:250},
    {desc:'wear boots (they are doc martens) (theyre expensive ($#Y) )', others:0, you:-200},
    {desc:'get caught by police for your various crimes. pay $#Y ticket', others:0, you:-150},
    {desc:'get paid $#Y more than men!', others:0, you:180},
    {desc:'start an onlyfans. collect $#Y', others:0, you:400},
    {desc:'get butt plug stuck in ass, go to ER, pay hospital bill of $#Y', others:0, you:-69},
    {desc:'buy a cute kitten! too bad theyre expensive. Pay $#Y', others:0, you:-250},
    {desc:'sell ur cat for $#Y', others:0, you:240},
    {desc:'land a modelling gig. earn $#Y.', others:0, you:300},
    {desc:'work at macdonal. earn $#Y.', others:0, you:100},
    {desc:'u r janet. Damnit janet! Lose $#Y.', others:0, you:-100},
    {desc:'So you were walking down the park street one day, and you saw a dumb guy. He was so dumb! You laughed and paid him $#Y for being so dumb', others:0, you:-50},
    {desc:'I ate an ass one time. Oops. Wrong card. Sorry for wasting your time. Here, take $#Y.', others:0, you:100},
    {desc:'Play the lick in front of Adam Neely. He loves it, and gives you $#Y.', others:0, you:75},
    {desc:'Go to the pickin palace with your friends. You all spend money!', others:50, you:-400},
    {desc:'Punch Judge. This one\'s free.', others:0, you:0},
    {desc:'be bisexual, twerk, eat hot chip, charge they phone, lie, spend $#Y', others:0, you:-200},
    {desc:'convince ur friends to buy into your MLM. They each pay $#O.', others:94, you:0},
    {desc:'wow iphone. win iphone worth $#Y.', others:0, you:125},
    {desc:'get bf. You get $#Y!', others:0, you:200},
    {desc:'Wow, you\'re dumb! Lose $#Y!', others:0, you:-97},
    {desc:'You cracked ur phone screen! Buy a new phone for $#Y', others:0, you:-220},
    {desc:'You feel sad for your friends. They\'re dying! In an effort to save them, you pay them each $#O.', others:-80, you:0},
    {desc:'You spend monopoly money at a store, saving you $#Y.', others:0, you:10},
    {desc:'Steal from walmart! Great savings indeed! You saved $#Y!', others:0, you:180},
    {desc:'Your dad died, and left you $#Y.', others:0, you:500},
    {desc:'Host a party! You\'ll spend $#Y on supplies.', others:0, you:-125},
    {desc:'Go on vacation! It better\'ve been good, because it cost you $#Y!', others:0, you:-300},
    {desc:'sell ur boobs for $#Y on ebay', others:0, you:340},
    {desc:'Put ur venmo in ur bio. People are giving you money! You earn $#T from this.', others:60, you:0},
    {desc:'Stream on twitch. Those simps donated $#T!', others:40, you:100},
    {desc:'Your friends are leaches! They stole $#T from you!', others:-30, you:0},
    {desc:'sell ur mom to a human trafficker for $#Y', others:0, you:112},
    {desc:'do some random kids homework for $#Y', others:0, you:25},
    {desc:'Get mugged! Lose $#Y.', others:0, you:-80},
    {desc:'go to halloween store, buy slutty cat costume for $#Y', others:0, you:-69},
    {desc:'Haha look at the funny man down there in the bottom right', others:0, you:0},
    {desc:'u r sus. to take heat off yourself, you give each of your friends $#O', others:-25, you:0},
    {desc:'You were speeding 48mph over in a school zone. Pay $#Y.', others:0, you:-350},
    {desc:'You are winner. Win $#Y.', others:0, you:100},
    {desc:'live', others:0, you:500},
    {desc:'ride in ambulance. Pay $#Y.', others:0, you:-250},
    {desc:'meet oaken. he bestows upon you $#Y', others:0, you:350},
    {desc:'eat at chilis. spend $#Y', others:0, you:-50},
    {desc:'lose $9999. ha u got trolled!! that was le epic. win $#Y', others:0, you:250},
    {desc:'ask ppl for money. every1 gives u $#O', others:20, you:0},
    {desc:'you get paid $#Y! wow! give each of ur friends $#O!', others:-20, you:200},
    {desc:'u were walkin in a circle when you found a piece of paper that was a $#Y bill', others:0, you:250},
    {desc:'its splurge time! spend $#Y!', others:0, you:-125},
    {desc:'ur playin some jazz, then you play a wrong note. thats p jazzy. Wow! crowds a cheerin\'. They pay you $#Y!', others:0, you:80},
    {desc:'ur a classical musican, then you play a wrong note. Boo you suck! Cry and lose $#Y.', others:0, you:-80},
    {desc:'you like to do laundry, so you launder $#Y.', others:0, you:300},
    {desc:'smoke a fat cig (if you must know, the cig was fancy and costed $#Y just for the one!)', others:0, you:-10},
    {desc:'pay some random ass $#Y to do your homework', others:0, you:-25},
    {desc:'you dumb bitch! You maxed out your credit card! That\'s gonna cost you $#Y!', others:0, you:-200},
    {desc:'You say: ok, ok, for reals now. You didnt really f my mom, did you? you did? well, then give me $#Y you dirty dumb', others:0, you:250},
    {desc:'gonna cry? piss and shit? maybe shit and cum? Thats what you get for losing $#Y', others:0, you:-150},
    {desc:'moto moto likes you. He bribes you with $#Y', others:0, you:250},
    {desc:'Damn daughter, whered ya find this $#Y?', others:0, you:300},
    {desc:'steal lunch money. Profit $#Y!!', others:0, you:20},
    {desc:'Stare at the sun! Ow! Why would you do that? Lose $#Y', others:0, you:-50},
    {desc:'Thank you for choosing draw card. Please accept this customary $#Y.', others:0, you:100},
    {desc:'1) play minecraft manhunt. 2) post it to youtube. 3) ?????? 4) profit $#Y', others:0, you:400},
    {desc:'open merch store. your merch is solid color w/ generic logo. Brilliant! You earn $#Y from this.', others:0, you:100}
];